title: Lucas Eloi # your name (or website title) here
logo: "/images/linkedin.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Olá, sou um analista de dados apaixonado por trabalhar com informações e números. Possuo vasta experiência em coleta, análise e visualização de dados, utilizando ferramentas como Python, SQL, Excel, Google Sheets, Tableau, Data Studio (lookerstudio) e Power BI.
  <br><br>
  <a href="https://www.linkedin.com/in/lucaseloi1/">View my LinkedIn Profile</a> 
  <br><br>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
